#include <stdio.h>

#include <cpu-features.h>

int main(void)
{
  uint64_t features;
  int cpus;

  features = android_getCpuFeatures();
  cpus = android_getCpuCount();

  #define CHECK_FEATURE(feature) if (features & feature) puts(#feature);

  printf("ANDROID_CPU_COUNT=%d\n", cpus);

  switch (android_getCpuFamily())
  {
  case ANDROID_CPU_FAMILY_ARM:
    puts("ANDROID_CPU_FAMILY_ARM");
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_VFPv3)
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_NEON)
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_LDREX_STREX)
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_VFPv2)
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_VFP_D32)
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_VFP_FP16)
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_VFP_FMA)
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_NEON_FMA)
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_IDIV_ARM)
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_IDIV_THUMB2)
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_iWMMXt)
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_AES)
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_PMULL)
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_SHA1)
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_SHA2)
    CHECK_FEATURE(ANDROID_CPU_ARM_FEATURE_CRC32)
    break;
  case ANDROID_CPU_FAMILY_X86:
    puts("ANDROID_CPU_FAMILY_X86");
    CHECK_FEATURE(ANDROID_CPU_X86_FEATURE_SSSE3)
    CHECK_FEATURE(ANDROID_CPU_X86_FEATURE_POPCNT)
    CHECK_FEATURE(ANDROID_CPU_X86_FEATURE_MOVBE)
    break;
  case ANDROID_CPU_FAMILY_MIPS:
    puts("ANDROID_CPU_FAMILY_MIPS");
    break;
  case ANDROID_CPU_FAMILY_ARM64:
    puts("ANDROID_CPU_FAMILY_ARM64");
    CHECK_FEATURE(ANDROID_CPU_ARM64_FEATURE_FP)
    CHECK_FEATURE(ANDROID_CPU_ARM64_FEATURE_ASIMD)
    CHECK_FEATURE(ANDROID_CPU_ARM64_FEATURE_AES)
    CHECK_FEATURE(ANDROID_CPU_ARM64_FEATURE_PMULL)
    CHECK_FEATURE(ANDROID_CPU_ARM64_FEATURE_SHA1)
    CHECK_FEATURE(ANDROID_CPU_ARM64_FEATURE_SHA2)
    CHECK_FEATURE(ANDROID_CPU_ARM64_FEATURE_CRC32)
    break;
  case ANDROID_CPU_FAMILY_X86_64:
    puts("ANDROID_CPU_FAMILY_X86_64");
    break;
  case ANDROID_CPU_FAMILY_MIPS64:
    puts("ANDROID_CPU_FAMILY_MIPS64");
    break;
  default:
    puts("ANDROID_CPU_FAMILY_UNKNOWN");
    break;
  }

  return 0;
}
